/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.esi.alg2.arbre.gui;

import be.esi.alg2.arbre.db.ArbreDB;
import be.esi.alg2.arbre.db.ArbreDbException;
import be.esi.alg2.arbre.dto.ArbreCompletDto;
import be.esi.alg2.arbre.dto.ArbreDto;
import be.esi.alg2.arbre.lancement.Accueil;
import be.esi.alg2.arbre.metier.ArbreBinaireFacade;
import be.esi.alg2.arbre.metier.ArbreMetierException;
import be.esi.alg2.arbre.mvc.Modele;
import be.esi.alg2.arbre.mvc.ProfondeurMaximaleAtteinteException;
import be.esi.alg2.arbre.mvc.Valeur;
import be.esi.alg2.gui.outils.MaJTableInitialisationException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author marty
 */
public class ChargerArbreDialog extends javax.swing.JDialog {

    /**
     * Creates new form ChargerArbre
     */
    private Modele modele;
    private String nom;

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }
    public ChargerArbreDialog(Accueil parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            tableArbre = new MaJTableArbre();
            tableArbre.setVisible(true);
            listePane.add(new JScrollPane(tableArbre));
            nom="";
        } catch (MaJTableInitialisationException ex) {
            JOptionPane.showMessageDialog(parent, ex.getMessage());
        }
        this.pack();

    }

    private ChargerArbreDialog(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            tableArbre = new MaJTableArbre();
            tableArbre.setVisible(true);
            listePane.add(new JScrollPane(tableArbre));

        } catch (MaJTableInitialisationException ex) {
            JOptionPane.showMessageDialog(parent, ex.getMessage());
        }
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rechPane = new javax.swing.JPanel();
        rechNomPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomArbreField = new javax.swing.JTextField();
        erreurLabel = new javax.swing.JLabel();
        rechButtonPane = new javax.swing.JPanel();
        rechButton = new javax.swing.JButton();
        listePane = new javax.swing.JPanel();
        selectPane = new javax.swing.JPanel();
        selectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rechPane.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Nom de l'arbre à charger : ");
        rechNomPane.add(jLabel1);

        nomArbreField.setColumns(30);
        rechNomPane.add(nomArbreField);

        erreurLabel.setForeground(new java.awt.Color(255, 0, 0));
        rechNomPane.add(erreurLabel);

        rechPane.add(rechNomPane, java.awt.BorderLayout.NORTH);

        rechButtonPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        rechButton.setText("Rechercher");
        rechButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechButtonActionPerformed(evt);
            }
        });
        rechButtonPane.add(rechButton);

        rechPane.add(rechButtonPane, java.awt.BorderLayout.SOUTH);

        getContentPane().add(rechPane, java.awt.BorderLayout.NORTH);
        getContentPane().add(listePane, java.awt.BorderLayout.CENTER);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT);
        flowLayout1.setAlignOnBaseline(true);
        selectPane.setLayout(flowLayout1);

        selectButton.setText("Selectionner");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });
        selectPane.add(selectButton);

        getContentPane().add(selectPane, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rechButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechButtonActionPerformed
        // TODO add your handling code here:
        List<ArbreDto> dto;
        try {

            dto = new ArrayList(ArbreBinaireFacade.getNomArbres(this.nomArbreField.getText()));
            tableArbre.setData(dto);
            if (dto.isEmpty()) {
                this.erreurLabel.setText("pas de clé [" + this.nomArbreField.getText() + "] trouvée");
            } else {
                this.erreurLabel.setText("");
            }
            this.pack();

        } catch (ArbreMetierException | ArbreDbException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }


    }//GEN-LAST:event_rechButtonActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        try {
            ArbreCompletDto arbreC = ArbreDB.chargeArbre(this.tableArbre.getSelectedObject().getId());
            ArbreBinaireFacade.getModele().nouvelArbre();
            this.modele = ArbreBinaireFacade.getModele();
            for (Valeur val : arbreC.getListe()) {
                this.modele.addValeur(val);
            }
            this.setNom(this.tableArbre.getSelectedObject().getId());
            this.dispose();
            
        } catch (ArbreDbException | ProfondeurMaximaleAtteinteException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_selectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChargerArbreDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChargerArbreDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChargerArbreDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChargerArbreDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChargerArbreDialog dialog;
                dialog = new ChargerArbreDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel erreurLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel listePane;
    private javax.swing.JTextField nomArbreField;
    private javax.swing.JButton rechButton;
    private javax.swing.JPanel rechButtonPane;
    private javax.swing.JPanel rechNomPane;
    private javax.swing.JPanel rechPane;
    private javax.swing.JButton selectButton;
    private javax.swing.JPanel selectPane;
    // End of variables declaration//GEN-END:variables
    private MaJTableArbre tableArbre;
}
